basePath: /
definitions:
  ds.Company:
    properties:
      company_id:
        type: integer
      description:
        type: string
      iin:
        type: string
      image_url:
        type: string
      name:
        type: string
      status:
        type: string
    type: object
  ds.CompanyList:
    properties:
      companies_list:
        items:
          $ref: '#/definitions/ds.Company'
        type: array
      draft_id:
        type: integer
    type: object
  ds.LoginSwaggerResp:
    properties:
      access_token:
        type: string
      expires_in:
        type: string
      token_type:
        type: string
    type: object
  ds.NewStatus:
    properties:
      status:
        type: string
      tender_id:
        type: integer
    type: object
  ds.RegisterReq:
    properties:
      login:
        type: string
      password:
        type: string
      user_name:
        type: string
    type: object
  ds.Tender:
    properties:
      company_tenders:
        items:
          $ref: '#/definitions/ds.TenderCompany'
        type: array
      completion_date:
        type: string
      creation_date:
        type: string
      formation_date:
        type: string
      id:
        type: integer
      moderator:
        $ref: '#/definitions/ds.User'
      moderator_id:
        type: integer
      status:
        type: string
      status_check:
        description: |-
          CreatorLogin    string          `json:"creator_login"`
          ModeratorLogin  string          `json:"moderator_login"`
        type: string
      tender_name:
        type: string
      user:
        $ref: '#/definitions/ds.User'
      user_id:
        type: integer
    type: object
  ds.TenderCompany:
    properties:
      cash:
        type: number
      company:
        $ref: '#/definitions/ds.Company'
      company_id:
        type: integer
      id:
        type: integer
      tender:
        $ref: '#/definitions/ds.Tender'
      tender_id:
        type: integer
    type: object
  ds.TenderDetails:
    properties:
      companies:
        items:
          $ref: '#/definitions/ds.Company'
        type: array
      tender:
        $ref: '#/definitions/ds.Tender'
    type: object
  ds.User:
    properties:
      id:
        type: integer
      login:
        maxLength: 64
        type: string
      name:
        type: string
      password:
        maxLength: 64
        minLength: 8
        type: string
      registrationDate:
        type: string
      role:
        $ref: '#/definitions/role.Role'
    required:
    - login
    - password
    type: object
  handler.errorResp:
    properties:
      error_description:
        type: string
      status:
        type: integer
    type: object
  role.Role:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - Buyer
    - Moderator
    - Admin
host: 127.0.0.1:8080
info:
  contact: {}
  description: App for serving tender requests
  title: Tender App
  version: "1.0"
paths:
  /api/companies:
    delete:
      consumes:
      - application/json
      description: Deletes a company with the given ID
      parameters:
      - description: Company ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema: {}
      summary: Delete company by ID
      tags:
      - Companies
    get:
      consumes:
      - application/json
      description: Companies List
      parameters:
      - description: Query string to filter companies by name
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.CompanyList'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Companies List
      tags:
      - Companies
    post:
      consumes:
      - multipart/form-data
      description: Add a new company with image, name, IIN
      parameters:
      - description: Company image
        in: formData
        name: image
        required: true
        type: file
      - description: Company name
        in: formData
        name: name
        required: true
        type: string
      - description: Company description
        in: formData
        name: description
        type: string
      - description: Company IIN
        in: formData
        name: IIN
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Add new company
      tags:
      - Companies
  /api/companies/:
    put:
      consumes:
      - multipart/form-data
      description: Updates a company with the given ID
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: name
        in: formData
        name: name
        type: string
      - description: description
        in: formData
        name: description
        type: string
      - description: IIN
        in: formData
        name: IIN
        type: string
      - description: image
        in: formData
        name: image
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema: {}
      summary: Update company by ID
      tags:
      - Companies
  /api/companies/{id}:
    get:
      consumes:
      - application/json
      description: Company By ID
      parameters:
      - description: Companies ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.Company'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Company By ID
      tags:
      - Companies
  /api/tender-request-company:
    delete:
      consumes:
      - application/json
      description: Deletes a company from a request based on the user ID and company
        ID
      parameters:
      - description: company ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema: {}
      summary: Delete company from request
      tags:
      - Tender_Company
    put:
      consumes:
      - application/json
      description: Update money Tender Company by client
      parameters:
      - description: Update money Tender Company
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ds.TenderCompany'
      produces:
      - application/json
      responses:
        "200":
          description: update
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update money Tender Company
      tags:
      - Tender_Company
  /api/tenders:
    delete:
      consumes:
      - application/json
      description: Deletes a tender request for the given user ID
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema: {}
      summary: Delete tender request by user ID
      tags:
      - Tenders
    get:
      consumes:
      - application/json
      description: Retrieves a list of tender requests based on the provided parameters
      parameters:
      - description: Tender request status
        in: query
        name: status
        type: string
      - description: Start date in the format '2006-01-02T15:04:05Z'
        in: query
        name: start
        type: string
      - description: End date in the format '2006-01-02T15:04:05Z'
        in: query
        name: end
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ds.Tender'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get list of tender requests
      tags:
      - Tenders
    put:
      consumes:
      - application/json
      description: Update Tender by admin
      parameters:
      - description: updated Assembly
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ds.Tender'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update Tender by admin
      tags:
      - Tenders
  /api/tenders/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves a tender request with the given ID
      parameters:
      - description: Tender Request ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.TenderDetails'
        "400":
          description: Bad Request
          schema: {}
      summary: Get tender request by ID
      tags:
      - Tenders
  /api/tenders/form:
    put:
      consumes:
      - application/json
      description: Form Company by client
      parameters:
      - description: Tender form ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.TenderDetails'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Form Company by client
      tags:
      - Tenders
  /api/v3/users/login:
    post:
      consumes:
      - application/json
      description: Вход нового пользователя.
      parameters:
      - description: Детали входа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ds.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: Успешная аутентификация
          schema:
            $ref: '#/definitions/ds.LoginSwaggerResp'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/handler.errorResp'
        "401":
          description: Неверные учетные данные
          schema:
            $ref: '#/definitions/handler.errorResp'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/handler.errorResp'
      summary: Аутентификация пользователя
      tags:
      - Пользователи
  /api/v3/users/logout:
    get:
      consumes:
      - application/json
      description: Завершение сеанса текущего пользователя.
      produces:
      - application/json
      responses:
        "200":
          description: Успешный выход
          schema:
            type: string
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/handler.errorResp'
        "401":
          description: Неверные учетные данные
          schema:
            $ref: '#/definitions/handler.errorResp'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/handler.errorResp'
      security:
      - ApiKeyAuth: []
      summary: Выход пользователя
      tags:
      - Пользователи
  /api/v3/users/sign_up:
    post:
      consumes:
      - application/json
      description: Регистрация нового пользователя.
      parameters:
      - description: Детали регистрации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ds.RegisterReq'
      produces:
      - application/json
      responses: {}
      summary: Регистрация пользователя
      tags:
      - Пользователи
  /companies/request:
    post:
      consumes:
      - application/json
      description: Adds a company to a tender request
      parameters:
      - description: Threat ID
        in: path
        name: threatId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema: {}
      summary: Add company to request
      tags:
      - Companies
  /tenders/updateStatus:
    put:
      consumes:
      - application/json
      description: Updates the status of a transaction request with the given ID on
        "завершен"/"отклонен"
      parameters:
      - description: Request ID
        in: path
        name: id
        required: true
        type: integer
      - description: update status
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ds.NewStatus'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema: {}
      summary: Update transaction request status by ID
      tags:
      - Tenders
schemes:
- http
swagger: "2.0"
